export const LOGIN = "LOGIN";
export const TRANSACTIONS = "TRANSACTIONS";
export const GET_CURRENCIES ="GET_CURRENCIES";
export const CREATE_TRANSACTION ="CREATE_TRANSACTION";
export const BANK_LIST = "BANK_LIST";
export const POST_TRANSACTIONS = "POST_TRANSACTIONS";
export const EXCHANGE_VERIFICATION = "EXCHANGE_VERIFICATION";
export const BANK_ACCOUNT = "BANK_ACCOUNT";
export const SIGN_OUT = "SIGN_OUT"

